package gitsemver_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	gitsemver "github.com/linkdata/gitsemver/internal/gitsemver"
)

func Test_VersionInfo_GoPackage(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.2.3", Branch: "mybranch", Build: "456"}

	txt, err := vi.GoPackage("../..", "", "", "")
	if err != nil {
		t.Error(err)
	}
	if !strings.Contains(txt, "package gitsemver") || !strings.Contains(txt, "const PkgName = \"gitsemver\"") {
		t.Error(txt)
	}
	if !strings.Contains(txt, "Code generated by "+gitsemver.PkgName+" "+gitsemver.PkgVersion+" DO NOT EDIT.") {
		t.Error(txt)
	}
	if strings.Contains(txt, " UTC DO NOT EDIT.") {
		t.Error("timestamp unexpectedly present in generated package header")
	}
	txt2, err := vi.GoPackage("../..", "", "", "")
	if err != nil {
		t.Fatal(err)
	}
	if txt != txt2 {
		t.Fatalf("expected deterministic gopackage output, got:\n1:%s\n2:%s", txt, txt2)
	}
	t.Log(txt)
	txt, err = vi.GoPackage("../..", "123", "", "")
	if err == nil {
		t.Error("no error")
	}
	if txt != "" {
		t.Error(txt)
	}
}

func Test_VersionInfo_GoPackage_ModuleWithInlineComment(t *testing.T) {
	repo := t.TempDir()
	goMod := "module example.com/my_pkg // inline comment\n\ngo 1.25\n"
	if err := os.WriteFile(filepath.Join(repo, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	vi := &gitsemver.VersionInfo{Tag: "v1.2.3", Branch: "mybranch", Build: "456"}
	txt, err := vi.GoPackage(repo, "", "", "")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(txt, "package my_pkg") || !strings.Contains(txt, "const PkgName = \"my_pkg\"") {
		t.Fatalf("unexpected generated package text: %s", txt)
	}
}

func Test_VersionInfo_GoPackage_RejectsKeywordAfterLowercasing(t *testing.T) {
	repo := t.TempDir()
	goMod := "module example.com/Type\n\ngo 1.25\n"
	if err := os.WriteFile(filepath.Join(repo, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	vi := &gitsemver.VersionInfo{Tag: "v1.2.3", Branch: "mybranch", Build: "456"}
	txt, err := vi.GoPackage(repo, "", "", "")
	if err == nil {
		t.Fatal("expected error")
	}
	if txt != "" {
		t.Fatalf("expected empty output, got %q", txt)
	}
}

func Test_VersionInfo_IncPatch(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.2", Tags: []gitsemver.GitTag{{Tag: "v1.2"}}}
	if !vi.HasTag("v1.2") {
		t.Error("!v1.2")
	}
	if vi.HasTag("v1.2.1") {
		t.Error("v1.2.1")
	}
	vi.IncPatch()
	if vi.Tag != "v1.2.1" {
		t.Error(vi.Tag)
	}
	vi.IncPatch()
	if vi.Tag != "v1.2.2" {
		t.Error(vi.Tag)
	}
}

func Test_VersionInfo_IncPatch_PrereleaseTag(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.2.3-rc.1"}
	if got := vi.IncPatch(); got != "v1.2.4" {
		t.Fatalf("expected v1.2.4, got %q", got)
	}
}

func Test_VersionInfo_IncPatch_AvoidsEquivalentVPrefixCollision(t *testing.T) {
	vi := &gitsemver.VersionInfo{
		Tag: "1.2.0",
		Tags: []gitsemver.GitTag{
			{Tag: "v1.2.1"},
		},
	}
	if got := vi.IncPatch(); got != "1.2.2" {
		t.Fatalf("expected 1.2.2, got %q", got)
	}
}

func Test_VersionInfo_IncPatch_AvoidsEquivalentNoPrefixCollision(t *testing.T) {
	vi := &gitsemver.VersionInfo{
		Tag: "v1.2.0",
		Tags: []gitsemver.GitTag{
			{Tag: "1.2.1"},
		},
	}
	if got := vi.IncPatch(); got != "v1.2.2" {
		t.Fatalf("expected v1.2.2, got %q", got)
	}
}

func Test_VersionInfo_IncPatch_InvalidTagNoLoop(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "not-a-semver-tag"}
	if got := vi.IncPatch(); got != "not-a-semver-tag" {
		t.Fatalf("expected unchanged tag, got %q", got)
	}
}

func Test_VersionInfo_IncPatch_OverflowPatchLevel(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.2.9999999999999999999999999"}
	if got := vi.IncPatch(); got != "v1.2.9999999999999999999999999" {
		t.Fatalf("expected unchanged overflow patch tag, got %q", got)
	}
}

func Test_VersionInfo_IncMinor_Mappings(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{in: "v1", want: "v1.1"},
		{in: "v1.2", want: "v1.3"},
		{in: "v1.2.3", want: "v1.3.0"},
	}
	for _, tt := range tests {
		vi := &gitsemver.VersionInfo{Tag: tt.in}
		if got := vi.IncMinor(); got != tt.want {
			t.Fatalf("IncMinor(%q): expected %q, got %q", tt.in, tt.want, got)
		}
		if !vi.SameTree {
			t.Fatalf("IncMinor(%q): expected SameTree=true", tt.in)
		}
	}
}

func Test_VersionInfo_IncMinor_PrereleaseTag(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.2.3-rc.1"}
	if got := vi.IncMinor(); got != "v1.3.0" {
		t.Fatalf("expected v1.3.0, got %q", got)
	}
	if !vi.SameTree {
		t.Fatal("expected SameTree=true")
	}
}

func Test_VersionInfo_IncMinor_AvoidsEquivalentPrefixCollisions(t *testing.T) {
	vi := &gitsemver.VersionInfo{
		Tag: "v1.2.3",
		Tags: []gitsemver.GitTag{
			{Tag: "v1.3.0"},
			{Tag: "1.4.0"},
		},
	}
	if got := vi.IncMinor(); got != "v1.5.0" {
		t.Fatalf("expected v1.5.0, got %q", got)
	}
}

func Test_VersionInfo_IncMinor_InvalidTagNoLoop(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "not-a-semver-tag"}
	if got := vi.IncMinor(); got != "not-a-semver-tag" {
		t.Fatalf("expected unchanged tag, got %q", got)
	}
	if !vi.SameTree {
		t.Fatal("expected SameTree=true for unchanged non-semver tag")
	}
}

func Test_VersionInfo_IncMinor_OverflowMinorLevel(t *testing.T) {
	vi := &gitsemver.VersionInfo{Tag: "v1.9999999999999999999999999"}
	if got := vi.IncMinor(); got != "v1.9999999999999999999999999" {
		t.Fatalf("expected unchanged overflow minor tag, got %q", got)
	}
	if !vi.SameTree {
		t.Fatal("expected SameTree=true for unchanged overflow tag")
	}
}

func Test_CleanBranch(t *testing.T) {
	isEqual(t, "branch-with-dots", gitsemver.CleanBranch("-branch.with..dots"))
	isEqual(t, "gitlab-branch", gitsemver.CleanBranch("gitlab---branch"))
	isEqual(t, "github-branch", gitsemver.CleanBranch("github.branch."))
	isEqual(t, "feature-x", gitsemver.CleanBranch("feature_x"))
}

func Test_VersionInfo_Version_UsesSemverSafeBranch(t *testing.T) {
	vi := &gitsemver.VersionInfo{
		Tag:       "v1.2.3",
		Branch:    "feature_x",
		Build:     "42",
		IsRelease: false,
		SameTree:  false,
	}
	if got := vi.Version(); got != "v1.2.3-feature-x.42" {
		t.Fatalf("expected semver-safe branch in version, got %q", got)
	}
}
